name: Bug report
description: Report a reproducible problem in Duckling
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report!

        Before submitting:
        - Search existing issues to avoid duplicates
        - If this is a security vulnerability, **do not** open a public issue — see `SECURITY.md`

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight checklist
      options:
        - label: I searched existing issues and didn’t find a duplicate
          required: true
        - label: This is not a security vulnerability (I read `SECURITY.md`)
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide steps so we can reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Upload/convert ...
        4. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened? Include any errors you saw.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs (backend/frontend) or add screenshots.
      placeholder: |
        - Backend logs (Flask/Gunicorn):
        - Frontend console/network logs:
        - Screenshots:
      render: shell
    validations:
      required: false

  - type: dropdown
    id: install
    attributes:
      label: How are you running Duckling?
      options:
        - Local dev (python + npm)
        - Docker (docker-compose)
        - Prebuilt images (docker-compose.prebuilt.yml)
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      description: e.g., macOS 15.2, Ubuntu 24.04, Windows 11
      placeholder: macOS 15.x
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
      description: e.g., 3.12.2
      placeholder: "3.12.x"
    validations:
      required: false

  - type: input
    id: node
    attributes:
      label: Node version
      description: e.g., 20.11.1
      placeholder: "20.x"
    validations:
      required: false

  - type: input
    id: duckling_version
    attributes:
      label: Duckling version / commit
      description: If known, include version tag or git commit SHA.
      placeholder: v2.4.0 / 1a2b3c4
    validations:
      required: false


