name: Question / support
description: Ask a question or get help using Duckling
title: "[Question]: "
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        Need help? You’re in the right place.

        Please include enough context so we can help quickly (what you tried, what you expected, what happened).

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight checklist
      options:
        - label: I searched existing issues and didn’t find an answer
          required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: What are you trying to do?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context / details
      description: Commands run, screenshots, logs, minimal repro, etc.
      render: shell
    validations:
      required: false


